### ISSUE TITLE
这个Tweak如何使用啊？

### ISSUE THREAD

**Issue by xuhuiandfish** [lemon4ex/ZeroTieriOSFix#1]
安装了官方ios的1.8.10 app了，如何使用你这个 tweak 替换自己的 planet 呢？

**Comment by lemon4ex** [comment]
先[按照文章](https://byteage.com/157.html)修改源码，编译生成planet文件，同时会在同一个目录(ZeroTierOne/attic/world)下生成一个新的`world.c`文件，打开这个文件，把里面的代码拷贝出来，替换掉`Tweak.x`里面对应的代码，然后编译Tweak。

**Comment by xuhuiandfish** [comment]
看着需要越狱啊？ 这一步门槛已经很高了

**Comment by lemon4ex** [comment]
> 看着需要越狱啊？ 这一步门槛已经很高了

需要越狱！话说回来，不越狱的话，iPhone手机组网好像也没什么意义吧？😂

**Comment by simonchen007** [comment]
> 看着需要越狱啊？ 这一步门槛已经很高了

可否用苹果开发者的证书签名这些IPA，然后实现免越狱安装呢？
@lemon4ex

**Comment by lemon4ex** [comment]
> > 看着需要越狱啊？ 这一步门槛已经很高了
> 
> 可否用苹果开发者的证书签名这些IPA，然后实现免越狱安装呢？ @lemon4ex

最新代码通过Hook OC 方法来实现，由于没有用到inlinehook，因此可以使用其他hook框架来重新实现同样的逻辑（比如使用runtime的方法替换，CaptionHook等），然后通过optool将生成的dylib注入到目标二进制文件，重新打包安装就可以。
需要注意的是，开发者账号配置的描述文件必须要有VPN相关的权限，否则无法使用。

**Comment by simonchen007** [comment]
@lemon4ex 
我们有开发者帐号，但是实际操作方式看不明白。
可否提供有偿服务？
我的联系方式 simon#yeacreate.com
