### ISSUE TITLE
 大佬，有做好的dylib或者deb不，想测试下自签和巨魔

### ISSUE THREAD

**Issue by wutaijieing** [lemon4ex/ZeroTieriOSFix#2]
不知道不越狱下自签和巨魔是否可以使用？

**Comment by lemon4ex** [comment]
不越狱不可以用，因为用到了hook sub_xxxx 的方式，非越狱的情况下不可以hook sub_xxxx。
还有，如果要使用自定义的服务器，需要修改代码并且自己编译一个动态库。
