### ISSUE TITLE
make编译报错

### ISSUE THREAD

**Issue by osmboy** [lemon4ex/ZeroTieriOSFix#3]
> Making all for tweak ZeroTieriOSFix…
==> Preprocessing Tweak.x…
==> Compiling Tweak.x (arm64)…
==> Linking tweak ZeroTieriOSFix (arm64)…
ld: warning: ignoring file /root/theos/sdks/iPhoneOS14.5.sdk/usr/lib/libobjc.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x0A 0x74 0x62 ) which is not the architecture being linked (arm64): /root/theos/sdks/iPhoneOS14.5.sdk/usr/lib/libobjc.tbdld: warning: ignoring file /root/theos/sdks/iPhoneOS14.5.sdk/System/Library/Frameworks//Foundation.framework/Foundation.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x0A 0x74 0x62 ) which is not the architecture being linked (arm64): /root/theos/sdks/iPhoneOS14.5.sdk/System/Library/Frameworks//Foundation.framework/Foundation.tbd

ld: warning: ignoring file /root/theos/sdks/iPhoneOS14.5.sdk/System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x0A 0x74 0x62 ) which is not the architecture being linked (arm64): /root/theos/sdks/iPhoneOS14.5.sdk/System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd
ld: warning: ignoring file /root/theos/sdks/iPhoneOS14.5.sdk/usr/lib/libc++.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x0A 0x74 0x62 ) which is not the architecture being linked (arm64): /root/theos/sdks/iPhoneOS14.5.sdk/usr/lib/libc++.tbd
ld: malformed file
/root/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd:2:42: error: unknown bit value
archs:           [ armv7, armv7s, arm64, arm64e, i386, x86_64 ]
                                         ^~~~~~
 file '/root/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/root/theos/makefiles/instance/library.mk:52: /root/ZeroTieriOSFix/.theos/obj/debug/arm64/ZeroTieriOSFix.dylib] Error 1
make[2]: *** [/root/theos/makefiles/instance/library.mk:52: /root/ZeroTieriOSFix/.theos/obj/debug/arm64/ZeroTieriOSFix.dylib] Error 2
make[1]: *** [/root/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
make: *** [/root/theos/makefiles/master/rules.mk:119: ZeroTieriOSFix.all.tweak.variables] Error 2

**Comment by lemon4ex** [comment]
在手机上编译？如果是，请换成在mac上编译，参考：https://iosgods.com/topic/104626-theos-error-arm64e/

**Comment by osmboy** [comment]
我在ubuntu上编译的，没有mac机器😳

**Comment by osmboy** [comment]
替换toolchain下载链接之后这个问题解决了：
原来的：
```shell
https://kabiroberai.com/toolchain/download.php?toolchain=ios-linux
```
现在的：
```shell
https://github.com/sbingner/llvm-project/releases/latest/download/linux-ios-arm64e-clang-toolchain.tar.lzma
```

**Comment by osmboy** [comment]
@lemon4ex 大佬，生成的deb文件可以通过ifile安装吗？

**Comment by lemon4ex** [comment]
必须可以啊 @osmboy

**Comment by osmboy** [comment]
@lemon4ex 大佬，我的ios 是16.02  硬件是iPhone 8p 有推荐的越狱工具吗？不越狱发现使用ifile安装不了

**Comment by lemon4ex** [comment]
1. deb 本来就是越狱设备才能安装的安装包类型，所以需要越狱
2. 越狱方法可以参考：https://www.ios-repo-updates.com/jailbreak/ ，根据自己的机型和系统看下是否有对应的越狱工具可以选择，根据你的系统版本，大概率是要用这个越狱工具，https://github.com/palera1n/palera1n  @osmboy

**Comment by osmboy** [comment]
@lemon4ex 好的，感谢大佬
