### ISSUE TITLE
请问：插件安装后无效过，该如何调试呢？

### ISSUE THREAD

**Issue by fathermrsing** [lemon4ex/ZeroTieriOSFix#4]
在编译的时候发现world.c 并没有生成（我把他给删除了没有看到文件生成,建了一个的空文件world.c数据仍然没有生成），导师控制台会输出需要的信息。插件编译安装一切正常，但是自己的控制器就是始终收不到加入网络的请求，版本也是1.8.10。能否分享下如何找到不同版本的地址便宜量的方法？

**Comment by lemon4ex** [comment]
找偏移量的方法只能参考开源的代码来找，虽然iOS的库和开源的不完全一样，但是有线索，这个一言两语说不清楚，你逆向看就会知道。

如果iOS手机app的版本是1.8.10，那应该不需要再找偏移。

编译的时候没有生成`world.c`文件应该是出错了吧？有成功生成planet可执行文件？

出现后台控制器收不到加入网络的请求，两种可能：

1. 要么服务器信息生成的有问题。
2. 插件安装后没效果。

第一点，如果你生成的planet文件在mac电脑上替换掉原始的文件后，mac电脑能成功加入网络，那说明文件没问题。

第二点，在上面一点确认planet文件生成没问题后，重点排查`越狱插件`为什么没生效。插件必须越狱设备才能用，非越狱设备除非打静态补丁，否则不可能会有效果。

调试插件主要还是使用`lldb+debugserver`的方式打断点调试，推荐使用[XcodeRootDebug](https://github.com/lemon4ex/XcodeRootDebug)

以上。

**Comment by fathermrsing** [comment]
感谢你的回复，但是我仍然没有成功。
1、我有成功生成world.bin,这个是没有报错,但是world.c确实内容没有修改，本地和服务器上通过源码编译都是这个情况。
另外，我用生成的planet 在macOS 上能正常加入和连接我的zerotier网络。在我的iPhone 5s（ios 10.3.3）上始终没有成功。
2、另一个问题看看大佬遇到过没有，我另外一台自建根服务器，加入我自己的服务器ip 和端口编译后，只有在重启macOS zerotier 客户端的服务时候服务端才能抓到包，但客户端始终没有收到数据包，导致这个客户端连接不上根服务。重启macos zerotier服务时，服务器抓包如下：
xx3.xx0.1.4.3819 > 10.0.0.250.9993: [udp sum ok] UDP, length 137
	0x0000:  0200 1700 23d6 0000 17ab d974 0800 4574  ....#......t..Et
	0x0010:  00a5 095f 0000 3011 bc9b b7dc 0104 0a00  ..._..0.........
	0x0020:  00fa 0eeb 2709 0091 75c2 8708 0c87 62c7  ....'...u.....b.
	0x0030:  6a21 6984 c8e1 7fe4 c1f4 df7d 007c 9016  j!i........}.|..
	0x0040:  9400 1d1c 1d01 0c01 0a00 0300 0001 86c5  ................
	0x0050:  3a05 63e4 c1f4 df7d 008c 05c1 d78f 11f8  :.c....}........
	0x0060:  8a00 d633 18cd 81c7 35a6 7850 994f 66c0  ...3....5.xP.Of.
	0x0070:  acbf 886a 39ee 5afa 116c 12b5 1c6c 325f  ...j9.Z..l...l2_
	0x0080:  adf7 ee0d 3672 8130 4577 b7fc 934b 6e09  ....6r.0Ew...Kn.
	0x0090:  e566 7c0b a06a fe00 ef00 04a8 8a45 5727  .f|..j.......EW'
	0x00a0:  0900 0000 0008 eac9 0a00 0001 6ce3 e239  ............l..9
	0x00b0:  5537 fe                                  U7.
15:15:59.771506 IP (tos 0x74, ttl 48, id 53268, offset 0, flags [none], proto UDP (17), length 165)
    xx3.xx0.1.4.27755 > 10.0.0.250.9993: [udp sum ok] UDP, length 137
	0x0000:  0200 1700 23d6 0000 17ab d974 0800 4574  ....#......t..Et
	0x0010:  00a5 d014 0000 3011 f5e5 b7dc 0104 0a00  ......0.........
	0x0020:  00fa 6c6b 2709 0091 1842 8708 0c87 62c7  ..lk'....B....b.
	0x0030:  6a21 6984 c8e1 7fe4 c1f4 df7d 007c 9016  j!i........}.|..
	0x0040:  9400 1d1c 1d01 0c01 0a00 0300 0001 86c5  ................
	0x0050:  3a05 63e4 c1f4 df7d 008c 05c1 d78f 11f8  :.c....}........
	0x0060:  8a00 d633 18cd 81c7 35a6 7850 994f 66c0  ...3....5.xP.Of.
	0x0070:  acbf 886a 39ee 5afa 116c 12b5 1c6c 325f  ...j9.Z..l...l2_
	0x0080:  adf7 ee0d 3672 8130 4577 b7fc 934b 6e09  ....6r.0Ew...Kn.
	0x0090:  e566 7c0b a06a fe00 ef00 04a8 8a45 5727  .f|..j.......EW'
	0x00a0:  0900 0000 0008 eac9 0a00 0001 6ce3 e239  ............l..9
	0x00b0:  5537 fe                                  U7.
15:15:59.771648 IP (tos 0x0, ttl 254, id 8909, offset 0, flags [none], proto UDP (17), length 87)
    10.0.0.250.9993 > xx3.xx0.1.4.3819: [no cksum] UDP, length 59
	0x0000:  0000 17ab d974 0200 1700 23d6 0800 4500  .....t....#...E.
	0x0010:  0057 22cd 0000 fe11 d5ee 0a00 00fa b7dc  .W".............
	0x0020:  0104 2709 0eeb 0043 0000 0bf5 1631 99a6  ..'....C.....1..
	0x0030:  11ac e4c1 f4df 7d69 84c8 e17f 18a4 f9a6  ......}i........
	0x0040:  ba7b 6e15 9660 4bcf d0dc c7c7 e1d5 5284  .{n..`K.......R.
	0x0050:  18a4 87f9 fa37 7b1a 2f8f 63a1 85e7 8f04  .....7{./.c.....
	0x0060:  0d5f f83c 2e                             ._.<.
15:15:59.771653 IP (tos 0x0, ttl 254, id 8910, offset 0, flags [none], proto UDP (17), length 165)
    10.0.0.250.9993 > xx3.xx0.1.4.3819: [no cksum] UDP, length 137
	0x0000:  0000 17ab d974 0200 1700 23d6 0800 4500  .....t....#...E.
	0x0010:  00a5 22ce 0000 fe11 d59f 0a00 00fa b7dc  ..".............
	0x0020:  0104 2709 0eeb 0091 0000 2545 7654 a3c9  ..'.......%EvT..
	0x0030:  781c e4c1 f4df 7d69 84c8 e17f 0054 87d0  x.....}i.....T..
	0x0040:  6d5c ebd7 2001 0c01 0a00 0100 0001 86c5  m\..............
	0x0050:  3a06 9b69 84c8 e17f 00be a67f 5b1e 2463  :..i........[.$c
	0x0060:  99f7 256b 7dce fb0d f67a 25d5 7d2f 9e36  ..%k}....z%.}/.6
	0x0070:  ca65 8c63 3f02 5307 0cbd 527c 0454 c1e5  .e.c?.S...R|.T..
	0x0080:  aefe 48f7 49f3 9896 065e f0d0 da40 c796  ..H.I....^...@..
	0x0090:  6015 7be0 c025 5cd4 a900 04b7 dc01 040e  `.{..%\.........
	0x00a0:  eb00 0000 0008 eac9 0a00 0001 6ce3 e239  ............l..9
	0x00b0:  5570 7e                                  Up~
15:15:59.771813 IP (tos 0x0, ttl 254, id 8913, offset 0, flags [none], proto UDP (17), length 87)
    10.0.0.250.9993 > xx3.xx0.1.4.27755: [no cksum] UDP, length 59
	0x0000:  0000 17ab d974 0200 1700 23d6 0800 4500  .....t....#...E.
	0x0010:  0057 22d1 0000 fe11 d5ea 0a00 00fa b7dc  .W".............
	0x0020:  0104 2709 6c6b 0043 0000 b6d4 0506 9ca1  ..'.lk.C........
	0x0030:  dea7 e4c1 f4df 7d69 84c8 e17f 1833 0fcb  ......}i.....3..
	0x0040:  ba99 78d8 1db2 75d8 e05e f21e c8e8 6750  ..x...u..^....gP
	0x0050:  c521 dc52 4497 10b8 4b9c 1d7d b7e8 4ddc  .!.RD...K..}..M.
	0x0060:  9fc9 cf9c ec                             .....
15:15:59.771866 IP (tos 0x0, ttl 254, id 8914, offset 0, flags [none], proto UDP (17), length 165)
    10.0.0.250.9993 > xx3.xx0.1.4.27755: [no cksum] UDP, length 137
	0x0000:  0000 17ab d974 0200 1700 23d6 0800 4500  .....t....#...E.
	0x0010:  00a5 22d2 0000 fe11 d59b 0a00 00fa b7dc  ..".............
	0x0020:  0104 2709 6c6b 0091 0000 b862 1779 a419  ..'.lk.....b.y..
	0x0030:  e8e4 e4c1 f4df 7d69 84c8 e17f 00ca d7d3  ......}i........
	0x0040:  8a66 2cef 2401 0c01 0a00 0100 0001 86c5  .f,.$...........
	0x0050:  3a06 9b69 84c8 e17f 00be a67f 5b1e 2463  :..i........[.$c
	0x0060:  99f7 256b 7dce fb0d f67a 25d5 7d2f 9e36  ..%k}....z%.}/.6
	0x0070:  ca65 8c63 3f02 5307 0cbd 527c 0454 c1e5  .e.c?.S...R|.T..
	0x0080:  aefe 48f7 49f3 9896 065e f0d0 da40 c796  ..H.I....^...@..
	0x0090:  6015 7be0 c025 5cd4 a900 04b7 dc01 046c  `.{..%\........l
	0x00a0:  6b00 0000 0008 eac9 0a00 0001 6ce3 e239  k...........l..9
	0x00b0:  55de 30                                  U.0
15:15:59.772370 IP (tos 0x74, ttl 48, id 20063, offset 0, flags [none], proto UDP (17), length 165)
    xx3.xx0.1.4.62209 > 10.0.0.250.9993: [udp sum ok] UDP, length 137
	0x0000:  0200 1700 23d6 0000 17ab d974 0800 4574  ....#......t..Et
	0x0010:  00a5 4e5f 0000 3011 779b b7dc 0104 0a00  ..N_..0.w.......
	0x0020:  00fa f301 2709 0091 91ab 8708 0c87 62c7  ....'.........b.
	0x0030:  6a21 6984 c8e1 7fe4 c1f4 df7d 007c 9016  j!i........}.|..
	0x0040:  9400 1d1c 1d01 0c01 0a00 0300 0001 86c5  ................
	0x0050:  3a05 63e4 c1f4 df7d 008c 05c1 d78f 11f8  :.c....}........
	0x0060:  8a00 d633 18cd 81c7 35a6 7850 994f 66c0  ...3....5.xP.Of.
	0x0070:  acbf 886a 39ee 5afa 116c 12b5 1c6c 325f  ...j9.Z..l...l2_
	0x0080:  adf7 ee0d 3672 8130 4577 b7fc 934b 6e09  ....6r.0Ew...Kn.
	0x0090:  e566 7c0b a06a fe00 ef00 04a8 8a45 5727  .f|..j.......EW'
	0x00a0:  0900 0000 0008 eac9 0a00 0001 6ce3 e239  ............l..9
	0x00b0:  5537 fe                                  U7.
15:15:59.772502 IP (tos 0x0, ttl 254, id 8917, offset 0, flags [none], proto UDP (17), length 87)
    10.0.0.250.9993 > xx3.xx0.1.4.62209: [no cksum] UDP, length 59
	0x0000:  0000 17ab d974 0200 1700 23d6 0800 4500  .....t....#...E.
	0x0010:  0057 22d5 0000 fe11 d5e6 0a00 00fa b7dc  .W".............
	0x0020:  0104 2709 f301 0043 0000 6f4d 61f2 7235  ..'....C..oMa.r5
	0x0030:  324f e4c1 f4df 7d69 84c8 e17f 1805 b753  2O....}i.......S
	0x0040:  a0f8 c9c1 c61e 5d07 5dd9 1956 2afd ad19  ......].]..V*...
	0x0050:  4227 961f 710d 1ad2 0fbe aa75 b362 388f  B'..q......u.b8.
	0x0060:  7e88 a55a 90                             ~..Z.
15:15:59.772559 IP (tos 0x0, ttl 254, id 8918, offset 0, flags [none], proto UDP (17), length 165)
    10.0.0.250.9993 > xx3.xx0.1.4.62209: [no cksum] UDP, length 137
	0x0000:  0000 17ab d974 0200 1700 23d6 0800 4500  .....t....#...E.
	0x0010:  00a5 22d6 0000 fe11 d597 0a00 00fa b7dc  ..".............
	0x0020:  0104 2709 f301 0091 0000 b6aa 4aa0 1284  ..'.........J...
	0x0030:  4b83 e4c1 f4df 7d69 84c8 e17f 004e cb22  K.....}i.....N."
	0x0040:  58ec f420 df01 0c01 0a00 0100 0001 86c5  X...............
	0x0050:  3a06 9c69 84c8 e17f 00be a67f 5b1e 2463  :..i........[.$c
	0x0060:  99f7 256b 7dce fb0d f67a 25d5 7d2f 9e36  ..%k}....z%.}/.6
	0x0070:  ca65 8c63 3f02 5307 0cbd 527c 0454 c1e5  .e.c?.S...R|.T..
	0x0080:  aefe 48f7 49f3 9896 065e f0d0 da40 c796  ..H.I....^...@..
	0x0090:  6015 7be0 c025 5cd4 a900 04b7 dc01 04f3  `.{..%\.........
	0x00a0:  0100 0000 0008 eac9 0a00 0001 6ce3 e239  ............l..9
	0x00b0:  5547 e7                                  UG.

**Comment by fathermrsing** [comment]
补充说明下，iPhone 5s是越狱了的

**Comment by lemon4ex** [comment]
> 我用生成的planet 在macOS 上能正常加入和连接我的zerotier网络
这里指的是连上了自己的根服务器对吧？那至少说明代码修改是没问题的。至于world.c没修改可能是源码的版本和我之前编译的不一样，我猜的。

手机始终无法成功的问题，直接上调试器调试或者源码打个日志，确定hook是否生效。

> 另一个问题看看大佬遇到过没有，我另外一台自建根服务器，加入我自己的服务器ip 和端口编译后，只有在重启macOS zerotier 客户端的服务时候服务端才能抓到包，但客户端始终没有收到数据包，

这个问题我没遇到，我有遇到的是 macOS 上的服务有时候会卡死，导致连不上服务器，需要重启服务才行。
